---
title: "p8105_hw1_lg3239"
author: "Landi Guo"
date: "2022-09-20"
output: github_document
editor_options: 
  chunk_output_type: console
---
## Problem 1
```{r, echo=FALSE}
library(ggplot2)
```


```{r}
# load in the penguins dataset
data("penguins", package = "palmerpenguins")
```

Details of the dataset:

```{r}
skimr::skim(penguins)
```

```{r}
# look at the actual table
View(penguins)
```

```{r}
# output the number of columns and rows for the dataset
ncol(penguins)
nrow(penguins)
```

This dataset has 344 rows and 8 columns, which consisting of 3 factor columns and 5 numeric columns. The column names are species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex, and year. There are 344 penguin subjects. The mean flipper length is 201mm.

```{r}
# ggplot() is used to load the penguins dataset with bill length on x-axis and flipper length on y-axis. The color is set to correspond species. geom_point() is used to generate scatter plot, and theme_minimal to change the gray background to white. labs() is used to specify plot title.

bill_flipper_plot = ggplot(data = penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) +
  geom_point() +
  theme_minimal() +
  labs(title = "flipper_length_mm vs bill_length_mm")
```

```{r}
# save the scatter plot above locally as a pdf
ggsave(filename = "hw1_plot.pdf", plot = bill_flipper_plot)
```

